global string $gShelfTopLevel;
string $currentShelf = `tabLayout -q -st $gShelfTopLevel`;
string $rootPath=`InstallLocationPath`;
string $pluginPath=$rootPath+"plug-ins/";
string $scriptPath=$rootPath+"scripts/";
string $iconsPath=$rootPath+"icons/";
string $uidPyPath=$scriptPath+"sdd_UIDNew.py";


shelfButton
    -command ("execfile('"+$uidPyPath+"')\r\nUIDesigner('"+$scriptPath+"').show()")
    -annotation "sdd_UIDesigner"
    -label ""
    -imageOverlayLabel ""
    -image ($iconsPath+"uid.bmp" )
    -image1 ($iconsPath+"uid.bmp")
    -sourceType "python"
    -parent $currentShelf;


global proc string InstallLocationPath ()
{
    string $whatIs=`whatIs InstallLocationPath`;
    string $fullPath=`substring $whatIs 25 999`;
    string $buffer[];
    int $numTok=`tokenize $fullPath "/" $buffer`;
    int $numLetters=size($fullPath);
    int $numLettersLastFolder=size($buffer[$numTok-1]);
    string $scriptLocation=`substring $fullPath 1 ($numLetters-$numLettersLastFolder)`;
    return $scriptLocation;
}