// FUNCTIONS
global proc float sinh(float $x) {
    $e = 2.718281828459;
    $ret = (pow($e, $x) - pow($e, -$x))/2;
    return($ret);
}
global proc float cosh(float $x) {
    $e = 2.718281828459;
    $ret = (pow($e, $x) + pow($e, -$x))/2;
    return($ret);
}
global proc float atanh(float $x) {
    $ret = 0.5 * log((1+$x)/(1-$x));
    return($ret);
}


global proc float xiaohongma_catenary_jiangsheng_auto_L_midCtrl(float $x, float $pt1x, float $pt1y, float $pt1z, float $pt2x, float $pt2y, float $pt2z, float $len) {
    // VARIABLES
    // $pt1x = jiangsheng_auto_L_startLoc.translateX;
    // $pt1y = jiangsheng_auto_L_startLoc.translateY;
    // $pt1z = jiangsheng_auto_L_startLoc.translateZ;

    // $pt2x = jiangsheng_auto_L_endLoc.translateX;
    // $pt2y = jiangsheng_auto_L_endLoc.translateY;
    // $pt2z = jiangsheng_auto_L_endLoc.translateZ;

    // $len = jiangsheng_auto_L_midCtrl_expr.length;

    // BASE DATA
    $dx = $pt2x - $pt1x;
    $dy = $pt2y - $pt1y;
    $dz = $pt2z - $pt1z;
    
    // CHECK DISTANCE
    $distance = sqrt(pow($dx, 2) + pow($dy, 2) + pow($dz, 2));
    $linear = $pt1y + ($x-$pt1x)*($dy/$dx);
    if ($len < $distance){
        return($linear);
    }

    // R
    $r = sqrt(pow($len, 2)-pow($dy, 2))/$dx;

    // ITERATION
    $A0 = log(2*$r)+log(log(2*$r));
    $A = $A0;
    for($i=0; $i<5; $i++){
        $A = $A - ((sinh($A) - ($r*$A))/(cosh($A)-$r));
    }

    // FINAL DATA
    $xb = ($pt1x + $pt2x)/2;

    $a = $dx/(2*$A);
    $b = $xb - $a*atanh($dy/$len);
    $c = $pt1y - $a*cosh(($pt1x-$b)/$a);

    // CALCULATION
    $catenary = $a*cosh(($x-$b)/$a) + $c;
    return($catenary);
}

jiangsheng_auto_L_mid_posGrp.translateY = xiaohongma_catenary_jiangsheng_auto_L_midCtrl(jiangsheng_auto_L_mid_posGrp.translateX, jiangsheng_auto_L_startLoc.translateX, jiangsheng_auto_L_startLoc.translateY, jiangsheng_auto_L_startLoc.translateZ,jiangsheng_auto_L_endLoc.translateX, jiangsheng_auto_L_endLoc.translateY, jiangsheng_auto_L_endLoc.translateZ,jiangsheng_auto_L_midCtrl_expr.length);