
    menuItem
        -label "Perspective View" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "switchModelView persp" 
        -optionBox 0
        -enable 1
        -visible 1
        -data 0
        -radialPosition "N" 
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuItem173;

    menuItem
        -label "FreezeTransformations" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "FreezeTransformations" 
        -optionBox 0
        -enable 1
        -visible 1
        -data 0
        -radialPosition "NW" 
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -image "FreezeTransform.png" 
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem2;

    menuItem
        -label "CenterPivot" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "CenterPivot" 
        -optionBox 0
        -enable 1
        -visible 1
        -data 0
        -radialPosition "NE" 
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -image "CenterPivot.png" 
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem3;

    menuItem
        -label "CVs" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "ToggleCVs" 
        -optionBox 0
        -enable 1
        -visible 1
        -data 0
        -radialPosition "S" 
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -image "menuIconDisplay.png" 
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem4;

    menuItem
        -label "ResetTransformations" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "ResetTransformations" 
        -optionBox 0
        -enable 1
        -visible 1
        -data 0
        -radialPosition "SE" 
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem5;

    menuItem
        -label "LocalRotationAxes" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "ToggleLocalRotationAxes" 
        -optionBox 0
        -enable 1
        -visible 1
        -data 0
        -radialPosition "SW" 
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -image "menuIconDisplay.png" 
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem6;

    menuItem
        -label "View" 
        -divider 0
        -subMenu 1
        -tearOff 0
        -optionBox 0
        -enable 1
        -visible 1
        -data 0
        -allowOptionBoxes 1
        -enableCommandRepeat 1
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem1;

        menuItem
            -label "Left View" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "MTviewChange(\"left\", \"-ls\");" 
            -optionBox 0
            -enable 1
            -visible 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem2;

        menuItem
            -label "Top View" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "switchModelView top" 
            -optionBox 0
            -enable 1
            -visible 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem3;

        menuItem
            -label "Back View" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "MTviewChange(\"back\", \"-b\");" 
            -optionBox 0
            -enable 1
            -visible 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem4;

        menuItem
            -label "Side View" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "switchModelView side" 
            -optionBox 0
            -enable 1
            -visible 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem5;

        menuItem
            -label "Bottom View" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "MTviewChange(\"bottom\", \"-bo\");" 
            -optionBox 0
            -enable 1
            -visible 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem6;

        menuItem
            -label "Front View" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "switchModelView front" 
            -optionBox 0
            -enable 1
            -visible 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem7;

    setParent -m ..;

    menuItem
        -label "separator" 
        -divider 1
        -dividerLabel "separator" 
        -subMenu 0
        -tearOff 0
        -optionBox 0
        -enable 1
        -visible 1
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem11;

    menuItem
        -label "Cluster" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "CreateCluster" 
        -optionBox 0
        -enable 1
        -visible 1
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -image "cluster.png" 
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem38;

    menuItem
        -label "menuEditorMenuItem53" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "CreateClusterOptions" 
        -optionBox 1
        -enable 1
        -visible 0
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 0
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem8;

    menuItem
        -label "CVCurve" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "CVCurveTool" 
        -optionBox 0
        -enable 1
        -visible 1
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -image "curveCV.png" 
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem7;

    menuItem
        -label "menuEditorMenuItem15" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "CVCurveToolOptions" 
        -optionBox 1
        -enable 1
        -visible 0
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 0
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem9;

    menuItem
        -label "RebuildCurve" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "RebuildCurve" 
        -optionBox 0
        -enable 1
        -visible 1
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -image "rebuildCurve.png" 
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem16;

    menuItem
        -label "menuEditorMenuItem18" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "RebuildCurveOptions" 
        -optionBox 1
        -enable 1
        -visible 0
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 0
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem13;

    menuItem
        -label "ReverseCurve" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "ReverseCurve" 
        -optionBox 0
        -enable 1
        -visible 1
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -image "reverse.png" 
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem32;

    menuItem
        -label "menuEditorMenuItem43" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "ReverseCurveOptions" 
        -optionBox 1
        -enable 1
        -visible 0
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 0
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem14;

    menuItem
        -label "Loft" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "Loft" 
        -optionBox 0
        -enable 1
        -visible 1
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -image "skin.png" 
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem12;

    menuItem
        -label "menuEditorMenuItem14" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "LoftOptions" 
        -optionBox 1
        -enable 1
        -visible 0
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 0
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem15;

    menuItem
        -label "RebuildSurfaces" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "RebuildSurfaces" 
        -optionBox 0
        -enable 1
        -visible 1
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -image "rebuildSurface.png" 
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem19;

    menuItem
        -label "menuEditorMenuItem21" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "RebuildSurfacesOptions" 
        -optionBox 1
        -enable 1
        -visible 0
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 0
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem17;

    menuItem
        -label "ReverseSurface" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "ReverseSurfaceDirection" 
        -optionBox 0
        -enable 1
        -visible 1
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -image "reverseSurface.png" 
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem22;

    menuItem
        -label "menuEditorMenuItem24" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "ReverseSurfaceDirectionOptions" 
        -optionBox 1
        -enable 1
        -visible 0
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 0
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem18;

    menuItem
        -label "Wrap" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "CreateWrap" 
        -optionBox 0
        -enable 1
        -visible 1
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -image "wrap.png" 
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem40;

    menuItem
        -label "menuEditorMenuItem63" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "CreateWrapOptions" 
        -optionBox 1
        -enable 1
        -visible 0
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 0
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem20;

    menuItem
        -label "Wire" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "WireTool" 
        -optionBox 0
        -enable 1
        -visible 1
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -image "wire.png" 
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem42;

    menuItem
        -label "menuEditorMenuItem67" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "WireToolOptions" 
        -optionBox 1
        -enable 1
        -visible 0
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 0
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem21;

    menuItem
        -label "AddBlendShape" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "AddBlendShape" 
        -optionBox 0
        -enable 1
        -visible 1
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -image "blendShapePlus.png" 
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem36;

    menuItem
        -label "menuEditorMenuItem70" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "AddBlendShapeOptions" 
        -optionBox 1
        -enable 1
        -visible 0
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 0
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem23;

    menuItem
        -label "NURBSToPolygons" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "NURBSToPolygons" 
        -optionBox 0
        -enable 1
        -visible 1
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -image "nurbsToPolygons.png" 
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem48;

    menuItem
        -label "menuEditorMenuItem54" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "NURBSToPolygonsOptions" 
        -optionBox 1
        -enable 1
        -visible 0
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 0
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem33;

    menuItem
        -label "CurveFromPoly" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "CreateCurveFromPoly" 
        -optionBox 0
        -enable 1
        -visible 1
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -image "polyEdgeToCurves.png" 
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem50;

    menuItem
        -label "menuEditorMenuItem58" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "CreateCurveFromPolyOptions" 
        -optionBox 1
        -enable 1
        -visible 0
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 0
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem34;

    menuItem
        -label "Sculpt" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "SculptGeometryTool" 
        -optionBox 0
        -enable 1
        -visible 1
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -image "putty.png" 
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem31;

    menuItem
        -label "menuEditorMenuItem35" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "SculptGeometryToolOptions" 
        -optionBox 1
        -enable 1
        -visible 0
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 0
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem35;

    menuItem
        -label "separator" 
        -divider 1
        -dividerLabel "separator" 
        -subMenu 0
        -tearOff 0
        -optionBox 0
        -enable 1
        -visible 1
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem10;

    menuItem
        -label "NamespaceEditor" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "NamespaceEditor" 
        -optionBox 0
        -enable 1
        -visible 1
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -image "namespaceEditor.png" 
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem24;

    menuItem
        -label "GraphEditor" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "GraphEditor" 
        -optionBox 0
        -enable 1
        -visible 1
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -image "teGraphEditor.png" 
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem25;

    menuItem
        -label "ComponentEditor" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "ComponentEditor" 
        -optionBox 0
        -enable 1
        -visible 1
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -image "componentTag_vertex.png" 
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem26;

    menuItem
        -label "ExpressionEditor" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "ExpressionEditor" 
        -optionBox 0
        -enable 1
        -visible 1
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -image "expression.svg" 
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem27;

    menuItem
        -label "DeformerSetEditor" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "DeformerSetEditor" 
        -optionBox 0
        -enable 1
        -visible 1
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -image "setEdit.png" 
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem28;

    menuItem
        -label "FilePathEditor" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "FilePathEditor" 
        -optionBox 0
        -enable 1
        -visible 1
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -image "file.png" 
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem30;

    menuItem
        -label "separator" 
        -divider 1
        -dividerLabel "separator" 
        -subMenu 0
        -tearOff 0
        -optionBox 0
        -enable 1
        -visible 1
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem29;

    menuItem
        -label "Hotbox Style" 
        -divider 0
        -subMenu 1
        -tearOff 0
        -optionBox 0
        -enable 1
        -visible 1
        -data 0
        -allowOptionBoxes 1
        -enableCommandRepeat 1
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuItem180;

        menuItem
            -label "Zones and Menu Rows" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "hotBox -dh" 
            -optionBox 0
            -enable 1
            -visible 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuItem181;

        menuItem
            -label "Zones Only" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "hotBox -dzo" 
            -optionBox 0
            -enable 1
            -visible 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuItem182;

        menuItem
            -label "Center Zone Only" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "hotBox -dco" 
            -optionBox 0
            -enable 1
            -visible 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuItem183;

    setParent -m ..;

setParent -m ..;

